-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.app_user
(
    user_id bigserial NOT NULL,
    name text COLLATE pg_catalog."default" NOT NULL,
    email text COLLATE pg_catalog."default" NOT NULL,
    password_hash text COLLATE pg_catalog."default" NOT NULL,
    role text COLLATE pg_catalog."default" NOT NULL,
    is_active boolean DEFAULT true,
    last_login timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT app_user_pkey PRIMARY KEY (user_id),
    CONSTRAINT uq_app_user_email UNIQUE (email)
);

COMMENT ON COLUMN public.app_user.name
    IS 'Display name (for interface, feedback)';

COMMENT ON COLUMN public.app_user.email
    IS 'Login name & Unique identifier (to prevent duplicate registration)';

COMMENT ON COLUMN public.app_user.is_active
    IS 'User disables/enables management';

CREATE TABLE IF NOT EXISTS public.assignment
(
    assignment_id bigserial NOT NULL,
    offering_id bigint NOT NULL,
    name text COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default",
    due_at timestamp without time zone,
    status text COLLATE pg_catalog."default",
    CONSTRAINT assignment_pkey PRIMARY KEY (assignment_id)
);

CREATE TABLE IF NOT EXISTS public.baseline_score
(
    baseline_id bigserial NOT NULL,
    assignment_id bigint NOT NULL,
    submission_id bigint NOT NULL,
    criterion_id bigint NOT NULL,
    score numeric(5, 2) NOT NULL,
    comment text COLLATE pg_catalog."default",
    scored_by bigint,
    CONSTRAINT baseline_score_pkey PRIMARY KEY (baseline_id),
    CONSTRAINT baseline_score_assignment_id_submission_id_criterion_id_key UNIQUE (assignment_id, submission_id, criterion_id)
);

CREATE TABLE IF NOT EXISTS public.course_offering
(
    offering_id bigserial NOT NULL,
    course_code text COLLATE pg_catalog."default" NOT NULL,
    term text COLLATE pg_catalog."default" NOT NULL,
    year integer NOT NULL,
    name text COLLATE pg_catalog."default",
    created_by bigint,
    CONSTRAINT course_offering_pkey PRIMARY KEY (offering_id)
);

CREATE TABLE IF NOT EXISTS public.feedback
(
    feedback_id bigserial NOT NULL,
    assignment_id bigint NOT NULL,
    marker_id bigint NOT NULL,
    submission_id bigint,
    content text COLLATE pg_catalog."default" NOT NULL,
    created_by bigint,
    created_at timestamp without time zone DEFAULT now(),
    title text COLLATE pg_catalog."default",
    CONSTRAINT feedback_pkey PRIMARY KEY (feedback_id)
);

CREATE TABLE IF NOT EXISTS public.invitations
(
    id serial NOT NULL,
    email character varying(255) COLLATE pg_catalog."default" NOT NULL,
    token character varying(255) COLLATE pg_catalog."default" NOT NULL,
    created_by bigint,
    created_at timestamp without time zone DEFAULT now(),
    expires_at timestamp without time zone NOT NULL,
    used_at timestamp without time zone,
    CONSTRAINT invitations_pkey PRIMARY KEY (id),
    CONSTRAINT invitations_token_key UNIQUE (token)
);

CREATE TABLE IF NOT EXISTS public.marker_score
(
    marker_score_id bigserial NOT NULL,
    assignment_id bigint NOT NULL,
    submission_id bigint NOT NULL,
    criterion_id bigint NOT NULL,
    marker_id bigint NOT NULL,
    score numeric(5, 2) NOT NULL,
    comment text COLLATE pg_catalog."default",
    submitted_at timestamp without time zone DEFAULT now(),
    finalized boolean DEFAULT false,
    CONSTRAINT marker_score_pkey PRIMARY KEY (marker_score_id)
);

CREATE TABLE IF NOT EXISTS public.rubric
(
    rubric_id bigserial NOT NULL,
    assignment_id bigint NOT NULL,
    uploaded_by bigint NOT NULL,
    CONSTRAINT rubric_pkey PRIMARY KEY (rubric_id)
);

CREATE TABLE IF NOT EXISTS public.rubric_criterion
(
    criterion_id bigserial NOT NULL,
    rubric_id bigint NOT NULL,
    seq_no integer NOT NULL,
    title text COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default",
    max_score numeric(5, 2) NOT NULL,
    CONSTRAINT rubric_criterion_pkey PRIMARY KEY (criterion_id)
);

CREATE TABLE IF NOT EXISTS public.submission
(
    submission_id bigserial NOT NULL,
    assignment_id bigint NOT NULL,
    sample_no integer NOT NULL,
    CONSTRAINT submission_pkey PRIMARY KEY (submission_id),
    CONSTRAINT uq_submission_assignment_sample UNIQUE (assignment_id, sample_no)
);

CREATE TABLE IF NOT EXISTS public.upload
(
    upload_id bigserial NOT NULL,
    assignment_id bigint,
    submission_id bigint,
    rubric_id bigint,
    file_name text COLLATE pg_catalog."default" NOT NULL,
    storage_path text COLLATE pg_catalog."default" NOT NULL,
    file_type text COLLATE pg_catalog."default" NOT NULL,
    owner_id integer,
    mime_type text COLLATE pg_catalog."default",
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT upload_pkey PRIMARY KEY (upload_id)
);

ALTER TABLE IF EXISTS public.assignment
    ADD CONSTRAINT assignment_offering_id_fkey FOREIGN KEY (offering_id)
    REFERENCES public.course_offering (offering_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_assignment_offering
    ON public.assignment(offering_id);


ALTER TABLE IF EXISTS public.baseline_score
    ADD CONSTRAINT baseline_score_assignment_id_fkey FOREIGN KEY (assignment_id)
    REFERENCES public.assignment (assignment_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_baseline_by_assignment
    ON public.baseline_score(assignment_id);


ALTER TABLE IF EXISTS public.baseline_score
    ADD CONSTRAINT baseline_score_criterion_id_fkey FOREIGN KEY (criterion_id)
    REFERENCES public.rubric_criterion (criterion_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_baseline_by_criterion
    ON public.baseline_score(criterion_id);


ALTER TABLE IF EXISTS public.baseline_score
    ADD CONSTRAINT baseline_score_scored_by_fkey FOREIGN KEY (scored_by)
    REFERENCES public.app_user (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.baseline_score
    ADD CONSTRAINT baseline_score_submission_id_fkey FOREIGN KEY (submission_id)
    REFERENCES public.submission (submission_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.course_offering
    ADD CONSTRAINT course_offering_created_by_fkey FOREIGN KEY (created_by)
    REFERENCES public.app_user (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.feedback
    ADD CONSTRAINT feedback_assignment_id_fkey FOREIGN KEY (assignment_id)
    REFERENCES public.assignment (assignment_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_feedback_assignment
    ON public.feedback(assignment_id);


ALTER TABLE IF EXISTS public.feedback
    ADD CONSTRAINT feedback_created_by_fkey FOREIGN KEY (created_by)
    REFERENCES public.app_user (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.feedback
    ADD CONSTRAINT feedback_marker_id_fkey FOREIGN KEY (marker_id)
    REFERENCES public.app_user (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_feedback_marker
    ON public.feedback(marker_id);


ALTER TABLE IF EXISTS public.feedback
    ADD CONSTRAINT feedback_submission_id_fkey FOREIGN KEY (submission_id)
    REFERENCES public.submission (submission_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.invitations
    ADD CONSTRAINT invitations_created_by_fkey FOREIGN KEY (created_by)
    REFERENCES public.app_user (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.marker_score
    ADD CONSTRAINT marker_score_assignment_id_fkey FOREIGN KEY (assignment_id)
    REFERENCES public.assignment (assignment_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_markerscore_assignment
    ON public.marker_score(assignment_id);


ALTER TABLE IF EXISTS public.marker_score
    ADD CONSTRAINT marker_score_criterion_id_fkey FOREIGN KEY (criterion_id)
    REFERENCES public.rubric_criterion (criterion_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_markerscore_criterion
    ON public.marker_score(criterion_id);


ALTER TABLE IF EXISTS public.marker_score
    ADD CONSTRAINT marker_score_marker_id_fkey FOREIGN KEY (marker_id)
    REFERENCES public.app_user (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_markerscore_marker
    ON public.marker_score(marker_id);


ALTER TABLE IF EXISTS public.marker_score
    ADD CONSTRAINT marker_score_submission_id_fkey FOREIGN KEY (submission_id)
    REFERENCES public.submission (submission_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_markerscore_submission
    ON public.marker_score(submission_id);


ALTER TABLE IF EXISTS public.rubric
    ADD CONSTRAINT rubric_assignment_id_fkey FOREIGN KEY (assignment_id)
    REFERENCES public.assignment (assignment_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_rubric_assignment
    ON public.rubric(assignment_id);


ALTER TABLE IF EXISTS public.rubric
    ADD CONSTRAINT rubric_uploaded_by_fkey FOREIGN KEY (uploaded_by)
    REFERENCES public.app_user (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.rubric_criterion
    ADD CONSTRAINT rubric_criterion_rubric_id_fkey FOREIGN KEY (rubric_id)
    REFERENCES public.rubric (rubric_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_rubric_criterion_rubric
    ON public.rubric_criterion(rubric_id);


ALTER TABLE IF EXISTS public.submission
    ADD CONSTRAINT submission_assignment_id_fkey FOREIGN KEY (assignment_id)
    REFERENCES public.assignment (assignment_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_submission_assignment
    ON public.submission(assignment_id);


ALTER TABLE IF EXISTS public.upload
    ADD CONSTRAINT upload_assignment_id_fkey FOREIGN KEY (assignment_id)
    REFERENCES public.assignment (assignment_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_upload_assignment
    ON public.upload(assignment_id);


ALTER TABLE IF EXISTS public.upload
    ADD CONSTRAINT upload_rubric_id_fkey FOREIGN KEY (rubric_id)
    REFERENCES public.rubric (rubric_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_upload_rubric
    ON public.upload(rubric_id);


ALTER TABLE IF EXISTS public.upload
    ADD CONSTRAINT upload_submission_id_fkey FOREIGN KEY (submission_id)
    REFERENCES public.submission (submission_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_upload_submission
    ON public.upload(submission_id);

END;