-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.

CREATE TYPE project_status AS ENUM ('draft', 'active', 'completed', 'archived');
BEGIN;


CREATE TABLE IF NOT EXISTS public.app_user
(
    user_id bigserial NOT NULL,
    name text COLLATE pg_catalog."default" NOT NULL,
    email text COLLATE pg_catalog."default" NOT NULL,
    password_hash text COLLATE pg_catalog."default" NOT NULL,
    role text COLLATE pg_catalog."default" NOT NULL,
    is_active boolean DEFAULT true,
    last_login timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT app_user_pkey PRIMARY KEY (user_id),
    CONSTRAINT uq_app_user_email UNIQUE (email)
);

COMMENT ON COLUMN public.app_user.name
    IS 'Display name (for interface, feedback)';

COMMENT ON COLUMN public.app_user.email
    IS 'Login name & Unique identifier (to prevent duplicate registration)';

COMMENT ON COLUMN public.app_user.is_active
    IS 'User disables/enables management';

CREATE TABLE IF NOT EXISTS public.assignment
(
    assignment_id bigserial NOT NULL,
    name text COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default",
    due_at timestamp without time zone NOT NULL,
    round smallint NOT NULL,
    project_id bigint,
    version integer DEFAULT 1,
    created_at timestamp without time zone DEFAULT now(),
    CONSTRAINT assignment_pkey PRIMARY KEY (assignment_id),
    CONSTRAINT uq_assignment_project_round_version UNIQUE (project_id, round, version)
);

CREATE TABLE IF NOT EXISTS public.baseline_score
(
    baseline_id bigserial NOT NULL,
    assignment_id bigint NOT NULL,
    criterion_id bigint NOT NULL,
    score numeric(5, 2) NOT NULL,
    comment text COLLATE pg_catalog."default",
    CONSTRAINT baseline_score_pkey PRIMARY KEY (baseline_id),
    CONSTRAINT uq_baseline_assignment_criterion UNIQUE (assignment_id, criterion_id)
);

CREATE TABLE IF NOT EXISTS public.criterion_grade_level
(
    grade_level_id bigserial NOT NULL,
    criterion_id bigint NOT NULL,
    level_name text COLLATE pg_catalog."default" NOT NULL,
    min_score numeric(5, 2) NOT NULL,
    max_score numeric(5, 2) NOT NULL,
    description text COLLATE pg_catalog."default",
    seq_no integer NOT NULL,
    CONSTRAINT criterion_grade_level_pkey PRIMARY KEY (grade_level_id)
);

CREATE TABLE IF NOT EXISTS public.feedback
(
    feedback_id bigserial NOT NULL,
    assignment_id bigint NOT NULL,
    marker_id bigint NOT NULL,
    content text COLLATE pg_catalog."default" NOT NULL,
    created_by bigint,
    created_at timestamp without time zone DEFAULT now(),
    title text COLLATE pg_catalog."default",
    CONSTRAINT feedback_pkey PRIMARY KEY (feedback_id)
);

CREATE TABLE IF NOT EXISTS public.invitations
(
    id serial NOT NULL,
    email character varying(255) COLLATE pg_catalog."default" NOT NULL,
    token character varying(255) COLLATE pg_catalog."default" NOT NULL,
    created_by bigint,
    created_at timestamp without time zone DEFAULT now(),
    expires_at timestamp without time zone NOT NULL,
    used_at timestamp without time zone,
    CONSTRAINT invitations_pkey PRIMARY KEY (id),
    CONSTRAINT invitations_token_key UNIQUE (token)
);

CREATE TABLE IF NOT EXISTS public.marker_score
(
    marker_score_id bigserial NOT NULL,
    assignment_id bigint NOT NULL,
    criterion_id bigint NOT NULL,
    marker_id bigint NOT NULL,
    score numeric(5, 2) NOT NULL,
    comment text COLLATE pg_catalog."default",
    submitted_at timestamp without time zone DEFAULT now(),
    finalized boolean DEFAULT false,
    CONSTRAINT marker_score_pkey PRIMARY KEY (marker_score_id),
    CONSTRAINT uq_marker_assignment_criterion UNIQUE (assignment_id, criterion_id, marker_id)
);

CREATE TABLE IF NOT EXISTS public.project
(
    project_id bigserial NOT NULL,
    name text COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default",
    created_at timestamp without time zone DEFAULT now(),
    created_by bigint,
    status project_status DEFAULT 'draft'::project_status,
    CONSTRAINT project_pkey PRIMARY KEY (project_id)
);

CREATE TABLE IF NOT EXISTS public.rubric
(
    rubric_id bigserial NOT NULL,
    uploaded_by bigint NOT NULL,
    "row" bigint,
    "column" bigint,
    project_id bigint,
    version integer DEFAULT 1,
    created_at timestamp without time zone DEFAULT now(),
    CONSTRAINT rubric_pkey PRIMARY KEY (rubric_id),
    CONSTRAINT uq_rubric_project_version UNIQUE (project_id, version)
);

CREATE TABLE IF NOT EXISTS public.rubric_criterion
(
    criterion_id bigserial NOT NULL,
    rubric_id bigint NOT NULL,
    seq_no integer NOT NULL,
    title text COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default",
    max_score numeric(5, 2) NOT NULL,
    CONSTRAINT rubric_criterion_pkey PRIMARY KEY (criterion_id)
);

CREATE TABLE IF NOT EXISTS public.upload
(
    upload_id bigserial NOT NULL,
    assignment_id bigint,
    rubric_id bigint,
    file_name text COLLATE pg_catalog."default" NOT NULL,
    storage_path text COLLATE pg_catalog."default" NOT NULL,
    file_type text COLLATE pg_catalog."default" NOT NULL,
    owner_id integer,
    mime_type text COLLATE pg_catalog."default",
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT upload_pkey PRIMARY KEY (upload_id)
);

ALTER TABLE IF EXISTS public.assignment
    ADD CONSTRAINT assignment_project_id_fkey FOREIGN KEY (project_id)
    REFERENCES public.project (project_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_assignment_project
    ON public.assignment(project_id);


ALTER TABLE IF EXISTS public.baseline_score
    ADD CONSTRAINT baseline_score_assignment_id_fkey FOREIGN KEY (assignment_id)
    REFERENCES public.assignment (assignment_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_baseline_by_assignment
    ON public.baseline_score(assignment_id);


ALTER TABLE IF EXISTS public.baseline_score
    ADD CONSTRAINT baseline_score_criterion_id_fkey FOREIGN KEY (criterion_id)
    REFERENCES public.rubric_criterion (criterion_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_baseline_by_criterion
    ON public.baseline_score(criterion_id);


ALTER TABLE IF EXISTS public.criterion_grade_level
    ADD CONSTRAINT fk_grade_level_criterion FOREIGN KEY (criterion_id)
    REFERENCES public.rubric_criterion (criterion_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_grade_level_criterion
    ON public.criterion_grade_level(criterion_id);


ALTER TABLE IF EXISTS public.feedback
    ADD CONSTRAINT feedback_assignment_id_fkey FOREIGN KEY (assignment_id)
    REFERENCES public.assignment (assignment_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_feedback_assignment
    ON public.feedback(assignment_id);


ALTER TABLE IF EXISTS public.feedback
    ADD CONSTRAINT feedback_created_by_fkey FOREIGN KEY (created_by)
    REFERENCES public.app_user (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.feedback
    ADD CONSTRAINT feedback_marker_id_fkey FOREIGN KEY (marker_id)
    REFERENCES public.app_user (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_feedback_marker
    ON public.feedback(marker_id);


ALTER TABLE IF EXISTS public.invitations
    ADD CONSTRAINT invitations_created_by_fkey FOREIGN KEY (created_by)
    REFERENCES public.app_user (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.marker_score
    ADD CONSTRAINT marker_score_assignment_id_fkey FOREIGN KEY (assignment_id)
    REFERENCES public.assignment (assignment_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_markerscore_assignment
    ON public.marker_score(assignment_id);


ALTER TABLE IF EXISTS public.marker_score
    ADD CONSTRAINT marker_score_criterion_id_fkey FOREIGN KEY (criterion_id)
    REFERENCES public.rubric_criterion (criterion_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_markerscore_criterion
    ON public.marker_score(criterion_id);


ALTER TABLE IF EXISTS public.marker_score
    ADD CONSTRAINT marker_score_marker_id_fkey FOREIGN KEY (marker_id)
    REFERENCES public.app_user (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_markerscore_marker
    ON public.marker_score(marker_id);


ALTER TABLE IF EXISTS public.project
    ADD CONSTRAINT project_created_by_fkey FOREIGN KEY (created_by)
    REFERENCES public.app_user (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.rubric
    ADD CONSTRAINT rubric_project_id_fkey FOREIGN KEY (project_id)
    REFERENCES public.project (project_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_rubric_project
    ON public.rubric(project_id);


ALTER TABLE IF EXISTS public.rubric
    ADD CONSTRAINT rubric_uploaded_by_fkey FOREIGN KEY (uploaded_by)
    REFERENCES public.app_user (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.rubric_criterion
    ADD CONSTRAINT rubric_criterion_rubric_id_fkey FOREIGN KEY (rubric_id)
    REFERENCES public.rubric (rubric_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_rubric_criterion_rubric
    ON public.rubric_criterion(rubric_id);


ALTER TABLE IF EXISTS public.upload
    ADD CONSTRAINT upload_assignment_id_fkey FOREIGN KEY (assignment_id)
    REFERENCES public.assignment (assignment_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_upload_assignment
    ON public.upload(assignment_id);


ALTER TABLE IF EXISTS public.upload
    ADD CONSTRAINT upload_rubric_id_fkey FOREIGN KEY (rubric_id)
    REFERENCES public.rubric (rubric_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_upload_rubric
    ON public.upload(rubric_id);

END;